name: Patch
on:
  workflow_dispatch:
    inputs:
      RECOVERY_URL:
        default: ''

jobs:
  Patch:
    runs-on: ubuntu-latest
    steps:
      - name: Patch
        run: |
          if [[ -n "${{ github.event.inputs.RECOVERY_URL }}" ]]; then
            aria2c "${{ github.event.inputs.RECOVERY_URL }}"
          else
            exit 1
          fi
          if [[ -e "recovery.img.lz4" ]]; then
            lz4 -d recovery.img.lz4 recovery.img
          elif [[ ! -e "recovery.img" ]]; then
            exit 1
          fi
          cp recovery.img r.img
          openssl genrsa -f4 -out phh.pem 4096
          MAGISK="$(curl -s "https://api.github.com/repos/topjohnwu/Magisk/releases/latest" | jq -r '.tag_name')"
          aria2c "https://github.com/topjohnwu/Magisk/releases/download/$MAGISK/Magisk-$MAGISK.apk"
          7z e Magisk-$MAGISK.apk lib/x86_64/libmagiskboot.so
          mkdir unpack output
          mv libmagiskboot.so ./unpack/magiskboot
          cd unpack
          chmod +x magiskboot
          ./magiskboot unpack ../r.img
          ./magiskboot cpio ramdisk.cpio extract
          set +e
          ./magiskboot hexpatch system/bin/recovery e10313aaf40300aa6ecc009420010034 e10313aaf40300aa6ecc0094
          ./magiskboot hexpatch system/bin/recovery eec3009420010034 eec3009420010035
          ./magiskboot hexpatch system/bin/recovery 3ad3009420010034 3ad3009420010035
          ./magiskboot hexpatch system/bin/recovery 50c0009420010034 50c0009420010035
          ./magiskboot hexpatch system/bin/recovery 080109aae80000b4 080109aae80000b5
          ./magiskboot hexpatch system/bin/recovery 20f0a6ef38b1681c 20f0a6ef38b9681c
          ./magiskboot hexpatch system/bin/recovery 23f03aed38b1681c 23f03aed38b9681c
          ./magiskboot hexpatch system/bin/recovery 20f09eef38b1681c 20f09eef38b9681c
          ./magiskboot hexpatch system/bin/recovery 26f0ceec30b1681c 26f0ceec30b9681c
          ./magiskboot hexpatch system/bin/recovery 24f0fcee30b1681c 24f0fcee30b9681c
          ./magiskboot hexpatch system/bin/recovery 27f02eeb30b1681c 27f02eeb30b9681c
          ./magiskboot hexpatch system/bin/recovery b4f082ee28b1701c b4f082ee28b970c1
          ./magiskboot hexpatch system/bin/recovery 9ef0f4ec28b1701c 9ef0f4ec28b9701c
          ./magiskboot hexpatch system/bin/recovery 9ef00ced28b1701c 9ef00ced28b9701c
          ./magiskboot hexpatch system/bin/recovery 2001597ae0000054 2001597ae1000054
          ./magiskboot hexpatch system/bin/recovery 24f0f2ea30b1681c 24f0f2ea30b9681c
          ./magiskboot hexpatch system/bin/recovery 41010054a0020012f44f48a9 4101005420008052f44f48a9
          set -e
          ./magiskboot cpio ramdisk.cpio 'add 0755 system/bin/recovery system/bin/recovery'
          ./magiskboot repack ../r.img new-boot.img
          cp new-boot.img ../r.img
          cd ..
          git clone https://android.googlesource.com/platform/external/avb --depth 1
          mv ./avb/avbtool.py avbtool
          python3 avbtool extract_public_key --key phh.pem --output phh.pub.bin
          python3 avbtool add_hash_footer --partition_name recovery --partition_size $(wc -c recovery.img | cut -d " " -f 1) --image r.img --key phh.pem --algorithm SHA256_RSA4096
          cd output
          mv ../r.img recovery.img
          tar cvf Patch-Recovery.tar recovery.img
          md5sum -t Patch-Recovery.tar >> Patch-Recovery.tar
          mv Patch-Recovery.tar Patch-Recovery.tar.md5
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Patched-Recovery
          path: ${{ github.workspace }}/output/Patch-Recovery.tar.md5